#
# Autogenerated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class ESFieldTypeEnum:
  STRING = 0
  BOOLEAN = 1
  SHORT = 2
  INT = 3
  LONG = 4
  DOUBLE = 5
  FLOAT = 6

  _VALUES_TO_NAMES = {
    0: "STRING",
    1: "BOOLEAN",
    2: "SHORT",
    3: "INT",
    4: "LONG",
    5: "DOUBLE",
    6: "FLOAT",
  }

  _NAMES_TO_VALUES = {
    "STRING": 0,
    "BOOLEAN": 1,
    "SHORT": 2,
    "INT": 3,
    "LONG": 4,
    "DOUBLE": 5,
    "FLOAT": 6,
  }

